config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :restaurants, except: [:edit, :update, :destroy] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: %w[chinese italian japanese french belgian]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render:new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_restaurant, only: %i[new create]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-light bg-light mb-5 sticky-top">
      Restaurants
      <div class="container-fluid">
        <a class="navbar-brand text-light fw-bold" href="/restaurants">Restaurants</a>
      </div>
    </nav>
    <div class="container col-6">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
  <%= link_to("Add a restaurant", new_restaurant_path, class: "btn btn-primary mb-5") %>

  <ul>
  <% @restaurants.each do |restaurant| %>
    <li class="mb-2">
      <%= link_to(restaurant.name, restaurant_path(restaurant))  %>
    </li>
  <% end  %>
  </ul>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, :collection => %w[chinese italian japanese french belgian] %>
  <%= f.input :phone_number %>
  <%= f.submit "Submit new restaurant", class: "btn btn-primary" %>
<% end %>


<p class="mt-5"><%= link_to("Back to hompage", restaurants_path) %></p>

app/views/restaurants/show.html.erb
<div class="col-6">
  <h1 class="border-bottom"><%= @restaurant.name %></h1>
  <p><%= link_to("Add a review", new_restaurant_review_path(@restaurant)) %></p>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>
  <p><%= @restaurant.category %></p>
</div>

<div class="col-6">
  <h2>Reviews</h2>
  <p class="border-bottom">
    <% @restaurant.reviews.reverse.each do |review| %>
    <li class="list-group-item">Rating: <%= review.rating %> <br><%= review.content %><br>Posted on: <%= review.created_at.strftime "%d/%m/%Y %Hh%M" %></li>
  <% end %>
  </p>
</div>



<%= link_to("Back to homepage", restaurants_path) %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, :collection => [0, 1, 2, 3, 4, 5] %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>


<%= link_to("Back to hompage", restaurants_path) %>